import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { makeProject, simpleAuto, writeAuto } from "../testSupport.js";
import { runCodegen } from "./codegen.js";

let root = "";
let out: string[] = [];

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "zenith-codegen-"));
  out = [];
  vi.spyOn(process.stdout, "write").mockImplementation((chunk: unknown) => {
    out.push(String(chunk));
    return true;
  });
});

afterEach(() => {
  vi.restoreAllMocks();
  rmSync(root, { recursive: true, force: true });
});

describe("zenith codegen", () => {
  it("writes the generated Java class under codegen.dir/<package path>/<PascalName>Generated.java", () => {
    makeProject(root);
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    const code = runCodegen("demo", { cwd: root });
    expect(code).toBe(0);
    const expected = join(root, "java/org/example/teamcode/opmode/Auto/DemoGenerated.java");
    expect(existsSync(expected)).toBe(true);
    const text = readFileSync(expected, "utf8");
    expect(text).toContain("public abstract class DemoGenerated extends AutoFromFile");
    expect(text).toContain("GENERATED by zenith from autos/demo.auto.json");
    expect(out.join("")).toContain("written:");
  });

  it('writes the Ivy form when deploy.commandLibrary is "ivy"', () => {
    makeProject(root, {
      deploy: { kind: "directory", dir: "deploy", commandLibrary: "ivy", robotClass: "org.example.teamcode.zenith.ExampleRobot" },
    });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(runCodegen("demo", { cwd: root })).toBe(0);
    const text = readFileSync(join(root, "java/org/example/teamcode/opmode/Auto/DemoGenerated.java"), "utf8");
    expect(text).toContain("import org.horizon36596.zenith.ivy.AutoFromFile;");
    expect(text).not.toContain("solverslib");
  });

  it("refuses to write a class until zenith.json names a command library", () => {
    makeProject(root, { deploy: undefined });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(() => runCodegen("demo", { cwd: root })).toThrow(/does not say which command library/);
    expect(existsSync(join(root, "java/org/example/teamcode/opmode/Auto/DemoGenerated.java"))).toBe(false);
  });

  it("does not write anything and exits 1 when the auto has a finding error", () => {
    makeProject(root);
    writeAuto(
      root,
      "autos",
      "crash",
      simpleAuto("crash", {
        start: { pose: { xIn: -20, yIn: 0, headingRad: 0 } },
        steps: [
          {
            id: "throughWall",
            kind: "path",
            segments: [{ kind: "line", from: "current", to: { xIn: 20, yIn: 0 } }],
            heading: { mode: "tangent" },
          },
        ],
      }),
    );
    const code = runCodegen("crash", { cwd: root });
    expect(code).toBe(1);
    expect(existsSync(join(root, "java"))).toBe(false);
  });

  it("throws a clear error when zenith.json has no codegen section", () => {
    makeProject(root, { codegen: undefined });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(() => runCodegen("demo", { cwd: root })).toThrow(/codegen/);
  });

  it("prints JSON with the written path and the source sha", () => {
    makeProject(root);
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    const code = runCodegen("demo", { cwd: root, json: true });
    expect(code).toBe(0);
    const parsed = JSON.parse(out.join("")) as { written: string; shaHex: string };
    expect(parsed.written).toContain("DemoGenerated.java");
    expect(parsed.shaHex).toMatch(/^[0-9a-f]{8}$/);
  });
});
