import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { hasErrors } from "@horizon36596/zenith-core";
import { loadAutoAndPlan } from "../autoLoad.js";
import { commandLibraryOf, LIBRARY_LABEL, RUNTIME_PACKAGE, type CommandLibrary } from "../commandLibrary.js";
import { pascalCase } from "../javaCodegen.js";
import { confinePath, loadProject, ProjectError, type Project } from "../project.js";

export interface DeployOptions {
  cwd?: string;
  project?: string;
  json?: boolean;
  dryRun?: boolean;
}

export type DeployActionKind = "copy" | "write" | "keep" | "remove" | "skip";

export interface DeployAction {
  kind: DeployActionKind;
  /** The path written, copied to or removed, relative to the project root. */
  path: string;
  /** Where a "copy" came from, relative to the project root. */
  from?: string;
  /** The bytes a "write" puts at `path`. Carried here so applying the plan needs no recomputation. */
  content?: string;
  /** Why a "skip" happened. */
  reason?: string;
}

const slash = (path: string): string => path.split("\\").join("/");

export interface StubOptions {
  packageName: string;
  className: string;
  autoName: string;
  title: string;
  relSource: string;
  /** `zenith.json` `deploy.robotClass`: the team's `ZenithRobot`, fully qualified. */
  robotClass: string;
  /** `zenith.json` `deploy.preselectTeleOp`; the annotation leaves it out when unset. */
  preselectTeleOp?: string;
  /** `zenith.json` `deploy.commandLibrary`: which runtime's classes the stub imports. */
  commandLibrary: CommandLibrary;
}

/**
 * One `@Autonomous` OpMode per auto file, extending the published runtime's `AutoFromFile`
 * (robot/README.md): `org.horizon36596.zenith.solverslib.AutoFromFile` for SolversLib, or
 * `org.horizon36596.zenith.ivy.AutoFromFile` for Ivy. It names the file and constructs the team's
 * robot; everything else is the runtime's.
 */
export function autoStub(options: StubOptions): string {
  const annotation = [`name = ${JSON.stringify(options.title)}`, `group = "Generated"`];
  if (options.preselectTeleOp !== undefined) {
    annotation.push(`preselectTeleOp = ${JSON.stringify(options.preselectTeleOp)}`);
  }
  const runtime = RUNTIME_PACKAGE[options.commandLibrary];
  return [
    `package ${options.packageName}.generated;`,
    "",
    "import com.qualcomm.robotcore.eventloop.opmode.Autonomous;",
    `import ${runtime}.AutoFromFile;`,
    `import ${runtime}.ZenithRobot;`,
    "",
    `/** GENERATED by zenith deploy from ${options.relSource}. Do not edit; edit the file and re-run zenith deploy. */`,
    `@Autonomous(${annotation.join(", ")})`,
    `public final class ${options.className} extends AutoFromFile {`,
    `    @Override protected String autoName() { return ${JSON.stringify(options.autoName)}; }`,
    `    @Override protected ZenithRobot createRobot() { return new ${options.robotClass}(); }`,
    "}",
    "",
  ].join("\n");
}

export interface DeployPlan {
  /**
   * The command library the stubs are written for, from `deploy.commandLibrary`. Undefined only when
   * `zenith.json` has no `codegen` section, so the deploy writes no Java, and names no library.
   */
  commandLibrary: CommandLibrary | undefined;
  actions: DeployAction[];
  /** Autos that failed `check()` and so were not copied or stubbed. */
  errors: number;
}

/** Works out every copy, stub write and stale-stub removal, without touching the filesystem. */
export function planDeploy(project: Project): DeployPlan {
  const actions: DeployAction[] = [];
  let errors = 0;
  const link = project.link;
  if (link.deploy === undefined) {
    throw new ProjectError('zenith.json has no "deploy" section; add one before running zenith deploy.');
  }

  // The OpMode stubs are the only Java a deploy writes, and it writes them only when zenith.json has a
  // "codegen" section; the data files it copies name no command library. So the library is required
  // exactly when there is a "codegen" section, and checked before anything else, so a project that has
  // not chosen one learns that first. Without "codegen", a library the file names is still reported.
  const commandLibrary = link.codegen === undefined ? link.deploy.commandLibrary : commandLibraryOf(link);

  const autosDirFull = join(project.root, link.autosDir);
  const autoFiles = existsSync(autosDirFull)
    ? readdirSync(autosDirFull).filter((name) => name.endsWith(".auto.json")).sort()
    : [];

  const deployed: { name: string; title: string; relPath: string }[] = [];
  for (const fileName of autoFiles) {
    const relPath = slash(join(link.autosDir, fileName));
    const result = loadAutoAndPlan(join(autosDirFull, fileName), project);
    if (!result.ok || hasErrors(result.loaded.findings)) {
      errors += 1;
      actions.push({ kind: "skip", path: relPath, reason: "has validation errors; run zenith validate" });
      continue;
    }
    deployed.push({
      name: result.loaded.auto.name,
      title: result.loaded.auto.title ?? result.loaded.auto.name,
      relPath,
    });
    actions.push({ kind: "copy", from: relPath, path: slash(join(link.deploy.dir, fileName)) });
  }

  if (link.waypoints !== undefined) {
    actions.push({
      kind: "copy",
      from: link.waypoints,
      path: slash(join(link.deploy.dir, basename(link.waypoints))),
    });
  }
  actions.push({ kind: "copy", from: link.robot, path: slash(join(link.deploy.dir, basename(link.robot))) });
  actions.push({ kind: "copy", from: link.field, path: slash(join(link.deploy.dir, basename(link.field))) });

  if (link.codegen !== undefined && commandLibrary !== undefined) {
    const codegen = link.codegen;
    const robotClass = link.deploy.robotClass;
    if (robotClass === undefined) {
      throw new ProjectError(
        'zenith.json has "codegen" but no "deploy.robotClass". Every OpMode zenith deploy writes constructs your ' +
          'robot: set "deploy.robotClass" to your ZenithRobot class, fully qualified ' +
          '(for example "org.firstinspires.ftc.teamcode.zenith.MyRobot"). See robot/README.md.',
      );
    }
    const preselectTeleOp = link.deploy.preselectTeleOp;
    const packagePath = codegen.package.split(".").join("/");
    const generatedDir = join(codegen.dir, packagePath, "generated");
    // codegen.dir itself was already confined to the project root by loadProject; packagePath comes
    // from codegen.package (a dotted Java package name) and is re-confined here too, so a package
    // name someone wrote as "..\\..\\evil" can't walk the generated-stub directory back out.
    const generatedDirFull = confinePath(project.root, generatedDir);
    const expected = new Map<string, string>(); // file name -> content

    for (const auto of deployed) {
      const fileName = `${pascalCase(auto.name)}Auto.java`;
      const className = fileName.replace(/\.java$/, "");
      expected.set(
        fileName,
        autoStub({
          packageName: codegen.package,
          className,
          autoName: auto.name,
          title: auto.title,
          relSource: auto.relPath,
          robotClass,
          ...(preselectTeleOp === undefined ? {} : { preselectTeleOp }),
          commandLibrary,
        }),
      );
    }

    const existing = existsSync(generatedDirFull)
      ? readdirSync(generatedDirFull).filter((name) => name.endsWith(".java"))
      : [];

    for (const [fileName, content] of expected) {
      const relStub = slash(join(generatedDir, fileName));
      const fullStub = join(generatedDirFull, fileName);
      const current = existsSync(fullStub) ? readFileSync(fullStub, "utf8") : null;
      actions.push({ kind: current === content ? "keep" : "write", path: relStub, content });
    }
    for (const fileName of existing) {
      if (expected.has(fileName)) continue;
      actions.push({ kind: "remove", path: slash(join(generatedDir, fileName)) });
    }
  }

  return { commandLibrary, actions, errors };
}

/** Performs the actions `planDeploy` worked out. `keep` and `skip` need nothing done. */
export function applyDeploy(project: Project, plan: DeployPlan): void {
  for (const action of plan.actions) {
    // The last line of defense before any write or delete: every action.path was built from
    // already-confined directories, but confining it again here, right at the filesystem call,
    // means this function alone is enough to guarantee deploy never touches anything outside the
    // project root (finding 13) even if a future action ever computed a path some other way.
    const full = confinePath(project.root, action.path);
    if (action.kind === "copy" && action.from !== undefined) {
      mkdirSync(dirname(full), { recursive: true });
      copyFileSync(confinePath(project.root, action.from), full);
    } else if (action.kind === "write" && action.content !== undefined) {
      mkdirSync(dirname(full), { recursive: true });
      writeFileSync(full, action.content, "utf8");
    } else if (action.kind === "remove") {
      rmSync(full, { force: true });
    }
  }
}

/**
 * `zenith deploy`: copies every valid auto plus `waypoints.json`, `robot.json` and the field file to
 * `zenith.json.deploy.dir`, and writes or refreshes one `@Autonomous` stub per auto under
 * `codegen.dir/<package>/generated/` (site/docs/robot-runtime.md), removing
 * stubs for autos that no longer exist. The stubs are written only when `zenith.json` has a `codegen`
 * section, and only then is `deploy.commandLibrary` required. `--dry-run` only lists what it would do.
 */
export function runDeploy(options: DeployOptions): number {
  const cwd = options.cwd ?? process.cwd();
  const project = loadProject(cwd, options.project);
  const plan = planDeploy(project);

  if (options.dryRun !== true) applyDeploy(project, plan);

  if (options.json === true) {
    process.stdout.write(
      `${JSON.stringify(
        {
          project: slash(project.root),
          dryRun: options.dryRun === true,
          commandLibrary: plan.commandLibrary ?? null,
          actions: plan.actions.map(({ content: _content, ...rest }) => rest),
          errors: plan.errors,
        },
        null,
        2,
      )}\n`,
    );
  } else {
    process.stdout.write(
      plan.commandLibrary === undefined
        ? 'command library: none named, and none needed: zenith.json has no "codegen" section, so no Java is written\n'
        : `command library: ${LIBRARY_LABEL[plan.commandLibrary]} (${RUNTIME_PACKAGE[plan.commandLibrary]})\n`,
    );
    for (const action of plan.actions) {
      const suffix = action.kind === "skip" ? ` (${action.reason ?? ""})` : "";
      process.stdout.write(`${action.kind}: ${action.path}${suffix}\n`);
    }
    process.stdout.write(`${String(plan.errors)} auto(s) skipped for validation errors\n`);
  }
  return plan.errors === 0 ? 0 : 1;
}
