import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { makeProject, simpleAuto, writeAuto } from "../testSupport.js";
import { runDeploy } from "./deploy.js";

let root = "";
let out: string[] = [];

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "zenith-deploy-"));
  out = [];
  vi.spyOn(process.stdout, "write").mockImplementation((chunk: unknown) => {
    out.push(String(chunk));
    return true;
  });
});

afterEach(() => {
  vi.restoreAllMocks();
  rmSync(root, { recursive: true, force: true });
});

describe("zenith deploy", () => {
  it("copies the auto, waypoints, robot and field files into deploy.dir and writes a stub", () => {
    makeProject(root);
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    const code = runDeploy({ cwd: root });
    expect(code).toBe(0);
    expect(existsSync(join(root, "deploy/demo.auto.json"))).toBe(true);
    expect(existsSync(join(root, "deploy/waypoints.json"))).toBe(true);
    expect(existsSync(join(root, "deploy/robot.json"))).toBe(true);
    expect(existsSync(join(root, "deploy/field.json"))).toBe(true);
    const stub = join(root, "java/org/example/teamcode/opmode/Auto/generated/DemoAuto.java");
    expect(existsSync(stub)).toBe(true);
    const text = readFileSync(stub, "utf8");
    expect(text).toContain("extends AutoFromFile");
    expect(text).toContain('return "demo";');
    expect(text).toContain("@Autonomous(");
  });

  it("writes a stub that extends the published runtime's AutoFromFile and constructs deploy.robotClass", () => {
    makeProject(root);
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(runDeploy({ cwd: root })).toBe(0);
    const stub = readFileSync(join(root, "java/org/example/teamcode/opmode/Auto/generated/DemoAuto.java"), "utf8");
    expect(stub).toBe(
      [
        "package org.example.teamcode.opmode.Auto.generated;",
        "",
        "import com.qualcomm.robotcore.eventloop.opmode.Autonomous;",
        "import org.horizon36596.zenith.solverslib.AutoFromFile;",
        "import org.horizon36596.zenith.solverslib.ZenithRobot;",
        "",
        "/** GENERATED by zenith deploy from autos/demo.auto.json. Do not edit; edit the file and re-run zenith deploy. */",
        '@Autonomous(name = "demo", group = "Generated")',
        "public final class DemoAuto extends AutoFromFile {",
        '    @Override protected String autoName() { return "demo"; }',
        "    @Override protected ZenithRobot createRobot() { return new org.example.teamcode.zenith.ExampleRobot(); }",
        "}",
        "",
      ].join("\n"),
    );
  });

  it("preselects the TeleOp named in deploy.preselectTeleOp, and only then", () => {
    makeProject(root, {
      deploy: {
        kind: "directory",
        dir: "deploy",
        commandLibrary: "solverslib",
        robotClass: "org.example.teamcode.zenith.ExampleRobot",
        preselectTeleOp: "Driver Control",
      },
    });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(runDeploy({ cwd: root })).toBe(0);
    const stub = readFileSync(join(root, "java/org/example/teamcode/opmode/Auto/generated/DemoAuto.java"), "utf8");
    expect(stub).toContain('@Autonomous(name = "demo", group = "Generated", preselectTeleOp = "Driver Control")');
  });

  it('writes stubs for the Ivy runtime when deploy.commandLibrary is "ivy"', () => {
    makeProject(root, {
      deploy: {
        kind: "directory",
        dir: "deploy",
        commandLibrary: "ivy",
        robotClass: "org.example.teamcode.zenith.ExampleRobot",
      },
    });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(runDeploy({ cwd: root })).toBe(0);
    const stub = readFileSync(join(root, "java/org/example/teamcode/opmode/Auto/generated/DemoAuto.java"), "utf8");
    expect(stub).toBe(
      [
        "package org.example.teamcode.opmode.Auto.generated;",
        "",
        "import com.qualcomm.robotcore.eventloop.opmode.Autonomous;",
        "import org.horizon36596.zenith.ivy.AutoFromFile;",
        "import org.horizon36596.zenith.ivy.ZenithRobot;",
        "",
        "/** GENERATED by zenith deploy from autos/demo.auto.json. Do not edit; edit the file and re-run zenith deploy. */",
        '@Autonomous(name = "demo", group = "Generated")',
        "public final class DemoAuto extends AutoFromFile {",
        '    @Override protected String autoName() { return "demo"; }',
        "    @Override protected ZenithRobot createRobot() { return new org.example.teamcode.zenith.ExampleRobot(); }",
        "}",
        "",
      ].join("\n"),
    );
    expect(out.join("")).toContain("command library: Ivy (org.horizon36596.zenith.ivy)\n");
  });

  it("refuses to deploy until zenith.json names a command library, and writes nothing", () => {
    makeProject(root, {
      deploy: { kind: "directory", dir: "deploy", robotClass: "org.example.teamcode.zenith.ExampleRobot" },
    });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(() => runDeploy({ cwd: root })).toThrow(
      /does not say which command library.*"commandLibrary": "solverslib" or "commandLibrary": "ivy"/,
    );
    expect(existsSync(join(root, "deploy"))).toBe(false);
    expect(existsSync(join(root, "java"))).toBe(false);
  });

  it("needs no command library when there is no codegen section, because it then writes no Java", () => {
    makeProject(root, {
      codegen: undefined,
      deploy: { kind: "directory", dir: "deploy", robotClass: "org.example.teamcode.zenith.ExampleRobot" },
    });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(runDeploy({ cwd: root })).toBe(0);
    expect(existsSync(join(root, "deploy/demo.auto.json"))).toBe(true);
    expect(existsSync(join(root, "deploy/robot.json"))).toBe(true);
    expect(existsSync(join(root, "java"))).toBe(false);
    const text = out.join("");
    expect(text).toMatch(/^command library: none named, and none needed: zenith\.json has no "codegen" section/);
    expect(text).not.toMatch(/^(write|keep|remove): .*\.java$/m);

    out = [];
    expect(runDeploy({ cwd: root, dryRun: true, json: true })).toBe(0);
    const json = JSON.parse(out.join("")) as { commandLibrary: unknown; actions: { kind: string; path: string }[] };
    expect(json.commandLibrary).toBeNull();
    expect(json.actions.every((action) => action.kind === "copy" && !action.path.endsWith(".java"))).toBe(true);
  });

  it("still reports a command library the file names when there is no codegen section", () => {
    makeProject(root, {
      codegen: undefined,
      deploy: { kind: "directory", dir: "deploy", commandLibrary: "ivy" },
    });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(runDeploy({ cwd: root, dryRun: true })).toBe(0);
    expect(out.join("")).toMatch(/^command library: Ivy \(org\.horizon36596\.zenith\.ivy\)\n/);
  });

  it("names the command library in its output", () => {
    makeProject(root);
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(runDeploy({ cwd: root, dryRun: true })).toBe(0);
    expect(out.join("")).toMatch(/^command library: SolversLib \(org\.horizon36596\.zenith\.solverslib\)\n/);

    out = [];
    expect(runDeploy({ cwd: root, dryRun: true, json: true })).toBe(0);
    expect(JSON.parse(out.join("")).commandLibrary).toBe("solverslib");
  });

  it("refuses a command library it does not know", () => {
    makeProject(root, {
      deploy: { kind: "directory", dir: "deploy", commandLibrary: "ftclib", robotClass: "a.B" },
    });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(() => runDeploy({ cwd: root })).toThrow(/commandLibrary/);
  });

  it("refuses to write stubs without deploy.robotClass, and says what to set", () => {
    makeProject(root, { deploy: { kind: "directory", dir: "deploy", commandLibrary: "solverslib" } });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(() => runDeploy({ cwd: root })).toThrow(/deploy\.robotClass/);
  });

  it("--dry-run lists the actions without writing anything", () => {
    makeProject(root);
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    const code = runDeploy({ cwd: root, dryRun: true });
    expect(code).toBe(0);
    expect(existsSync(join(root, "deploy"))).toBe(false);
    expect(out.join("")).toContain("copy:");
  });

  it("skips an auto with a finding error and reports it, but still deploys the valid ones", () => {
    makeProject(root);
    writeAuto(root, "autos", "good", simpleAuto("good"));
    writeAuto(
      root,
      "autos",
      "bad",
      simpleAuto("bad", {
        start: { pose: { xIn: -20, yIn: 0, headingRad: 0 } },
        steps: [
          {
            id: "throughWall",
            kind: "path",
            segments: [{ kind: "line", from: "current", to: { xIn: 20, yIn: 0 } }],
            heading: { mode: "tangent" },
          },
        ],
      }),
    );
    const code = runDeploy({ cwd: root });
    expect(code).toBe(1);
    expect(existsSync(join(root, "deploy/good.auto.json"))).toBe(true);
    expect(existsSync(join(root, "deploy/bad.auto.json"))).toBe(false);
  });

  it("removes a stub for an auto that no longer exists", () => {
    makeProject(root);
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    runDeploy({ cwd: root });
    const stub = join(root, "java/org/example/teamcode/opmode/Auto/generated/DemoAuto.java");
    expect(existsSync(stub)).toBe(true);

    rmSync(join(root, "autos/demo.auto.json"));
    const code = runDeploy({ cwd: root });
    expect(code).toBe(0);
    expect(existsSync(stub)).toBe(false);
  });

  it("keeps an unchanged stub rather than rewriting it", () => {
    makeProject(root);
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    runDeploy({ cwd: root });
    const stub = join(root, "java/org/example/teamcode/opmode/Auto/generated/DemoAuto.java");
    const before = readFileSync(stub, "utf8");

    out = [];
    const code = runDeploy({ cwd: root });
    expect(code).toBe(0);
    expect(readFileSync(stub, "utf8")).toBe(before);
    expect(out.join("")).toContain("keep:");
  });

  it("throws a clear error when zenith.json has no deploy section", () => {
    makeProject(root, { deploy: undefined });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(() => runDeploy({ cwd: root })).toThrow(/deploy/);
  });

  it("finding 13: refuses a deploy.dir that escapes the project root, and never creates it", () => {
    makeProject(root, { deploy: { kind: "directory", dir: "../ESCAPED" } });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(() => runDeploy({ cwd: root })).toThrow(/resolves outside the project root/);
    expect(existsSync(join(root, "..", "ESCAPED"))).toBe(false);
  });

  it("finding 13: refuses a codegen.dir that escapes the project root, and never creates it", () => {
    makeProject(root, { codegen: { package: "org.example.teamcode.opmode.Auto", dir: "../ESCAPED-CODEGEN" } });
    writeAuto(root, "autos", "demo", simpleAuto("demo"));
    expect(() => runDeploy({ cwd: root })).toThrow(/resolves outside the project root/);
    expect(existsSync(join(root, "..", "ESCAPED-CODEGEN"))).toBe(false);
  });

  it("finding 13: refuses an absolute deploy.dir outside the project root", () => {
    const outside = mkdtempSync(join(tmpdir(), "zenith-deploy-outside-"));
    try {
      makeProject(root, { deploy: { kind: "directory", dir: join(outside, "ESCAPED") } });
      writeAuto(root, "autos", "demo", simpleAuto("demo"));
      expect(() => runDeploy({ cwd: root })).toThrow(/resolves outside the project root/);
      expect(existsSync(join(outside, "ESCAPED"))).toBe(false);
    } finally {
      rmSync(outside, { recursive: true, force: true });
    }
  });
});

/** The starter example, copied to a scratch directory so deploy never writes into the repository. */
const starter = fileURLToPath(new URL("../../../../examples/starter", import.meta.url));

describe.skipIf(!existsSync(join(starter, "zenith.json")))("zenith deploy on the starter example", () => {
  it("writes the first-auto OpMode the robot runtime README shows", () => {
    cpSync(starter, root, { recursive: true });
    expect(runDeploy({ cwd: root })).toBe(0);
    expect(existsSync(join(root, "TeamCode/src/main/assets/autos/first-auto.auto.json"))).toBe(true);
    const stub = readFileSync(
      join(root, "TeamCode/src/main/java/org/firstinspires/ftc/teamcode/zenith/generated/FirstAutoAuto.java"),
      "utf8",
    );
    expect(stub).toBe(
      [
        "package org.firstinspires.ftc.teamcode.zenith.generated;",
        "",
        "import com.qualcomm.robotcore.eventloop.opmode.Autonomous;",
        "import org.horizon36596.zenith.solverslib.AutoFromFile;",
        "import org.horizon36596.zenith.solverslib.ZenithRobot;",
        "",
        "/** GENERATED by zenith deploy from autos/first-auto.auto.json. Do not edit; edit the file and re-run zenith deploy. */",
        '@Autonomous(name = "First auto", group = "Generated")',
        "public final class FirstAutoAuto extends AutoFromFile {",
        '    @Override protected String autoName() { return "first-auto"; }',
        "    @Override protected ZenithRobot createRobot() { return new org.firstinspires.ftc.teamcode.zenith.MyRobot(); }",
        "}",
        "",
      ].join("\n"),
    );
  });
});
